version: "3.8"

services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${EMAIL:-fake@mail.local}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --log
      - --api
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-public-http.rule=Host(`traefik.${DOMAIN:-local}`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-https.rule=Host(`traefik.${DOMAIN:-local}`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - traefik-data:/certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '80:80'
      - '443:443'

  php:
    image: aartintelligent/app-php:${PHP_VERSION:-latest}
    labels:
      - traefik.enable=true
      - traefik.http.routers.php-http.rule=Host(`php.${DOMAIN:-local}`)
      - traefik.http.routers.php-http.entrypoints=http
      - traefik.http.routers.php-http.middlewares=https-redirect
      - traefik.http.routers.php-https.rule=Host(`php.${DOMAIN:-local}`)
      - traefik.http.routers.php-https.entrypoints=https
      - traefik.http.routers.php-https.tls=true
      - traefik.http.routers.php-https.tls.certresolver=le
      - traefik.http.services.php.loadbalancer.server.port=8080
    volumes:
      - ./src:/var/www:rw,delegated
    depends_on:
      - traefik

volumes:
  traefik-data:
